

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - BACKEND_API_URL=${BACKEND_API_URL}
    container_name: wefixit-frontend
    ports:
      - "3069:3069"
    restart: unless-stopped
    env_file:
      - .env
